### PR TITLE
Update carbon credit and offer fields from integer to string

### LINKED ISSUE #118: Update cct_totalsupply, offer_amount and offer_total_price response type
To avoid errors in parse the JSON response of the methods that return `cct_totalsupply`, `offer_amount` and `offer_total_price` it is necessary to return these values ​​in string format instead of integer

Methods that use these fields:

`/token/{nft_id}`
`/scttreasury/offer`
`/scttreasury/offer/{offer_id}`

@cawabunga @lucasdcoutinh0

### LINKED ISSUE #119: Update POST /token and POST /scttreasury/deposit amount type from integer/number to string
Through tests, we detected the need to change some fields types from integer/number to string. Just as in the task #118 , the same must be done in methods that receive big numbers as parameters. In this way,  the `amount` field in the `POST /token` and `POST /scttreasury/deposit` methods needs to be updated from integer/number to string.

@cawabunga @lucasdcoutinh0

### PR DESCRIPTION
**Pull request by freitasgouvea**
This PR solves the issues #118 and #119 to prevent javascript big number overflow:

- Update `cct_carboncredittoken` model `cct_totalsupply` field
- Update `offer_carbontreasuryoffer`model `offer_amount` and `offer_total_price` fields
- Update `token` and `deposit` schema validators
- Update cron_event service offer fields
- Update readme
- Update unit tests to test big number cases

Endpoints requests and responses updated:

`GET /token/{nft_id}`
`POST /token`
`POST /scttreasury/deposit` 
`GET /scttreasury/offer`
`GET /scttreasury/offer/{offer_id}`

Closed #118 
Closed #119

### CODE REVIEW

**Review by jeffprestes — CHANGES_REQUESTED** [review]
LGTM. 
However, before merge it I'd wait for @cawabunga , @lucasdcoutinh0 and @raaha 's reviews

**Comment by freitasgouvea** [comment]
After the merge, for the changes to take effect, it is necessary to update our database:

```
ALTER TABLE public.cct_carboncredittoken ALTER COLUMN  cct_totalsupply type varchar(255) USING cct_totalsupply::varchar(255);
ALTER TABLE public.offer_carbontreasuryoffer ALTER COLUMN  offer_amount type varchar(255) USING offer_amount::varchar(255);
ALTER TABLE public.offer_carbontreasuryoffer ALTER COLUMN  offer_total_price type varchar(255) USING offer_total_price::varchar(255);
```

**Review by raaha — APPROVED** [review]
LGTM. Let me know if you need my help to deploy this version.

**Review by lucasdcoutinh0 — APPROVED** [review]

**Review by cawabunga — APPROVED** [review]
Not sure if all places are handled, because I'm not so familiar with the codebase, however changes looks good.

**Review by jeffprestes — APPROVED** [review]

**Pull request merged**
